### ISSUE TITLE
Color calculation doesn't seem to work on mobile

### ISSUE THREAD

**Issue by jessepinho** [matkl/average-color#5]
![fullsizeoutput_39c7](https://user-images.githubusercontent.com/1121544/36203044-706e6152-1186-11e8-8145-a2e7c1c9b766.jpeg)

I'll look into this when I have more time, but it appears something is broken on mobile. Just wanted to open an issue so I don't forget about it.

**Comment by jessepinho** [comment]
Hm, this may be an iOS bug. I'm noticing that it only seems to happen for images that haven't already been re-downloaded to my phone from iCloud. When a photo has already been downloaded, it works fine.

**Comment by matkl** [comment]
It works fine in Chrome 64 on Android.

**Comment by jessepinho** [comment]
OK. I'll close for now unless I can confirm that it's an issue with this repo and not with iOS.
